// <auto-generated />
using System;
using EverWave.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EverWave.Data.Migrations
{
    [DbContext(typeof(EverWaveContext))]
    partial class EverWaveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CargoMembro", b =>
                {
                    b.Property<int>("CargosId")
                        .HasColumnType("integer");

                    b.Property<Guid>("MembrosId")
                        .HasColumnType("uuid");

                    b.HasKey("CargosId", "MembrosId");

                    b.HasIndex("MembrosId");

                    b.ToTable("CargoMembro");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaCargoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaCargoId");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.CategoriaCargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CategoriaCargo");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ddi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("MembroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MembroId");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.Membro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UnidadeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Membros");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.Ministerio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MembroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MembroId");

                    b.ToTable("Ministerios");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.MinisterioLocal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MinisterioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("UnidadeId", "MinisterioId");

                    b.HasIndex("MinisterioId");

                    b.ToTable("MinisteriosLocais");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.ParticipacaoMinisterioLocal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid");

                    b.Property<int>("CargoId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InactivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MembroId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MinisterioLocalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasAlternateKey("MinisterioLocalId", "MembroId", "CargoId");

                    b.HasIndex("CargoId1");

                    b.HasIndex("MembroId");

                    b.ToTable("ParticipacoesMinisteriosLocais");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("CargoMembro", b =>
                {
                    b.HasOne("EverWave.Domain.Entities.Cargo", null)
                        .WithMany()
                        .HasForeignKey("CargosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EverWave.Domain.Entities.Membro", null)
                        .WithMany()
                        .HasForeignKey("MembrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EverWave.Domain.Entities.Cargo", b =>
                {
                    b.HasOne("EverWave.Domain.Entities.CategoriaCargo", "Categoria")
                        .WithMany("Cargos")
                        .HasForeignKey("CategoriaCargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.Contato", b =>
                {
                    b.HasOne("EverWave.Domain.Entities.Membro", "Membro")
                        .WithMany("Contatos")
                        .HasForeignKey("MembroId");

                    b.Navigation("Membro");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.Membro", b =>
                {
                    b.HasOne("EverWave.Domain.Entities.Unidade", "Unidade")
                        .WithMany("Membros")
                        .HasForeignKey("UnidadeId");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.Ministerio", b =>
                {
                    b.HasOne("EverWave.Domain.Entities.Membro", null)
                        .WithMany("Ministerios")
                        .HasForeignKey("MembroId");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.MinisterioLocal", b =>
                {
                    b.HasOne("EverWave.Domain.Entities.Ministerio", "Ministerio")
                        .WithMany("MinisteriosLocais")
                        .HasForeignKey("MinisterioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EverWave.Domain.Entities.Unidade", "Unidade")
                        .WithMany("MinisteriosLocais")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ministerio");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.ParticipacaoMinisterioLocal", b =>
                {
                    b.HasOne("EverWave.Domain.Entities.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EverWave.Domain.Entities.Membro", "Membro")
                        .WithMany()
                        .HasForeignKey("MembroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EverWave.Domain.Entities.MinisterioLocal", "MinisterioLocal")
                        .WithMany("ParticipacoesMinisterios")
                        .HasForeignKey("MinisterioLocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Membro");

                    b.Navigation("MinisterioLocal");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.CategoriaCargo", b =>
                {
                    b.Navigation("Cargos");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.Membro", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Ministerios");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.Ministerio", b =>
                {
                    b.Navigation("MinisteriosLocais");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.MinisterioLocal", b =>
                {
                    b.Navigation("ParticipacoesMinisterios");
                });

            modelBuilder.Entity("EverWave.Domain.Entities.Unidade", b =>
                {
                    b.Navigation("Membros");

                    b.Navigation("MinisteriosLocais");
                });
#pragma warning restore 612, 618
        }
    }
}
